// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SistemaAtualEmprestimo.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SistemaAtualEmprestimo.Models
{
    public partial interface IEmprestimoAtualContextProcedures
    {
        Task<int> DevolucaoAsync(int? Id_LivroCliente, int? qtd, OutputParameter<string> Retorno, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> EmprestimoAsync(int? id_livro, int? id_cliente, int? qtd, OutputParameter<string> Retorno, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Inserir_LivrosAsync(string nome, string autor, string editora, int? edicao, int? qtd, DateTime? data_lancamento, OutputParameter<string> retorno, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InserirClienteAsync(string BI, string Nome, string Mun, int? Contacto, OutputParameter<string> Retorno, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
